### ISSUE TITLE
Error:Cross-fitting fold 1 RMSPE_cv not found

### ISSUE THREAD

**Issue by marshzhao** [aahrens1/ddml#31]
The example code provided in the "Interactive model--ATE and ATET estimation" method at the ddml help file has a mistake.

This is the example code:
'''
webuse cattaneo2, clear

global Y bweight
global D mbsmoke
global X prenatal1 mmarried fbaby mage medu
set seed 42

ddml init interactive, kfolds(5) reps(5)

ddml E[Y|X,D]: pystacked $Y $X, type(reg) methods(ols gradboost)
ddml E[D|X]: pystacked $D $X, type(class) methods(logit gradboost)

ddml crossfit

ddml estimate
ddml estimate, atet
'''

Run this code and get a ”Cross-fitting fold 1 RMSPE_cv not found“ error, probably some problems with the ols and logit parameter calls.

**Comment by aahrens1** [comment]
Your code runs for me. Are you using the latest version of `ddml`?

```
net install ddml, from(https://raw.githubusercontent.com/aahrens1/ddml/master) replace
```

**Comment by marshzhao** [comment]
`net install ddml, from(https://raw.githubusercontent.com/aahrens1/ddml/master) replace`
notes "host not found"
How can I directly download commands?

**Comment by aahrens1** [comment]
> If you want to use ddml in an offline environment, we recommend to download the packages from the Github repositories. The links to repositories are above; click the green button “Code” and “Download ZIP”. Then run net install as above but from() should refer to the downloaded and unzipped repository folder.

https://statalasso.github.io/docs/ddml/installation/

Link to repository: https://github.com/aahrens1/ddml

**Comment by marshzhao** [comment]
I am using the latest version of ddml now,but the error still occur.This is log.
`-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
      name:  <unnamed>
       log:  C:\Users\Administrator\Desktop\Academic_win\method\data\SAlogs.log
  log type:  text
 opened on:   5 Apr 2023, 21:46:47

. *DDML Interactive model--ATE and ATET estimation
. use "C:\Users\Administrator\Desktop\Academic_win\method\data\cattaneo2", clear
(Excerpt from Cattaneo (2010) Journal of Econometrics 155: 138-154)

. 
. global Y bweight

. global D mbsmoke

. global X prenatal1 mmarried fbaby mage medu

. 
. 
. set seed 42

. 
. 
. ddml init interactive, kfolds(5) reps(5)

. 
. ddml E[Y|X,D]: pystacked $Y $X, type(reg) methods(ols gradboost)
Learner Y1_pystacked added successfully.

. ddml E[D|X]: pystacked $D $X, type(class) methods(ols gradboost)
Learner D1_pystacked added successfully.

. 
. 
. ddml crossfit
Cross-fitting E[y|X,D] equation: bweight
Resample 1...
Cross-fitting fold 1 RMSPE_cv not found
r(111);

end of do-file

r(111);

. exit, clear
`

**Comment by aahrens1** [comment]
You have a typo in your code: 

```
ddml E[D|X]: pystacked $D $X, type(class) methods(ols gradboost)
```

should be 

```
ddml E[D|X]: pystacked $D $X, type(class) methods(logit gradboost)
```

We have tested this on multiple machines using the latest versions of ddml and pystacked, and it should run if you correct the above typo.

**Comment by marshzhao** [comment]
I am sorry,it's my mistake.
Thank you!
