### ISSUE TITLE
how to predict in test partition

### ISSUE THREAD

**Issue by LPecht** [aahrens1/ddml#38]
Hi, It is not clear to me how to predict in a test partition (svar==2).

Tried unsuccessfully:

. ddml init partial if svar ==1, kfolds(2)
warning - model m0 already exists
all existing model results and variables will
be dropped and model m0 will be re-initialized

. ddml E[Y|X]: pystacked $Y `covars', type(reg) method(rf)
Learner Y1_pystacked added successfully.

. ddml E[D|X]: pystacked $D `covars', type(reg) method(rf)
Learner D1_pystacked added successfully.

. ddml crossfit
Cross-fitting E[y|X] equation: sales
Cross-fitting fold 1 2 ...completed cross-fitting
Cross-fitting E[D|X] equation: price
Cross-fitting fold 1 2 ...completed cross-fitting

.  predict double yhat if svar ==2
**error: data in memory has changed since last -pystacked- call
you are not allowed to change data in memory between -pystacked- fit and -predict-
r(198);**

**Comment by aahrens1** [comment]
The purpose of `ddml` is to estimate causal parameters rather than to predict. If you want to predict out-of-sample, have a look at our `pystacked` command.
