### ISSUE TITLE
Allow for non-binary D with `interactiveiv`

### ISSUE THREAD

**Issue by a-torgovitsky** [aahrens1/ddml#39]
With a multivalued ordered treatment (D), the `interactiveiv` estimator can be interpreted as estimating the average causal response introduced in Angrist and Imbens (1995, _JASA_). This follows from arguments in Frolich (2007, _JoE_).

Currently, an error is thrown if D is not binary:
```stata
. ddml crossfit, shortstack finalest(nnls1) nostdstack
error - interactiveiv model supported only for D=0 or D=1
```

It would be better not to throw an error.

@thomaswiemann and I have discussed this for the `ddml` R package and the change was made a couple of months ago and uploaded to CRAN.

**Comment by aahrens1** [comment]
Thanks @a-torgovitsky ! Excellent point. I have removed the restriction in the [dev](https://github.com/aahrens1/ddml/tree/dev) version, which we will upgrade to the main version soon.
